### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'lmtools'

### ISSUE THREAD

**Issue by mnhauke** [kaiiorg/check_flexlm#1]
I get the following error when running check_flexlm:

```
$ ./check_flexlm.py --lmutil /usr/bin/lmutil --server 1.2.3.4 --port 1234
Traceback (most recent call last):
  File "./check_flexlm.py", line 130, in <module>
    args.lmtools,
AttributeError: 'Namespace' object has no attribute 'lmtools'
```

Tested python versions 3.8.6 and 2.7.18

**Comment by kaiiorg** [comment]
Sorry for the late reply, I didn't have notification for this repo turned on.

Edit: I misread the error, let me look at this a bit closer.

**Comment by kaiiorg** [comment]
@mnhauke Ok, I think I fixed it. 

Sorry for the trouble. This was a script that I rewrote on my personal time in a more sane way than my prototype that I wrote at work, so I didn't have a way of testing it.

**Comment by mnhauke** [comment]
https://github.com/kaiiorg/check_flexlm/commit/2a4570dd946bd86ce0f60cc223a5a9352716721e fixed it, thanks!
